### ISSUE TITLE
友情链接出现这个问题

### ISSUE THREAD

**Issue by 490694561** [Siphils/Typecho-Theme-Aria#1]
Deprecated: Non-static method Shortcode::shortcode_linkbox() should not be called statically in /www/wwwroot/0xpoker.ctfer.org/usr/themes/Aria/lib/Shortcode.php on line 70

**Comment by Siphils** [comment]
目前暂时的解决办法：
打开`lib/Shortcode.php`文件，找到第587和599行
将`public function`修改为`public static function`
下个版本会修复这个问题

**Comment by 490694561** [comment]
谢谢，能顺便优化下导航栏的解析吗，我现在是写对了也不给通过

**Comment by Siphils** [comment]
可能你没写对，注意需要严格按照格式填写，可以仔细参照使用帮助里的例子[导航栏配置](https://github.com/Siphils/Typecho-Theme-Aria/blob/master/README.md#user-content-%E5%AF%BC%E8%88%AA%E6%A0%8F%E9%85%8D%E7%BD%AE)
