### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by SlippyJimmy** [Siphils/Typecho-Theme-Aria#11]
作者你的主题很漂亮，我非常喜欢。但是有些许不足：
       PC端浏览器浏览窗口化时主显示区域和两侧空白区域的比例感觉很舒服，但是全屏放大后只有两则空白区域拉伸，而文字区域大小不变----这样显示下来文字区域基本只占1/3，分布比例不协调。请问能同步拉伸吗？
![缩小](https://ws1.sinaimg.cn/thumbnail/007rzGmgly1fxrjhvi64bj30xe0nvk8t.jpg)
![放大](https://ws1.sinaimg.cn/thumbnail/007rzGmgly1fxrjg0theyj31hc0u0kft.jpg)
> 环境 
系统 macOS 
浏览器 Chrome/Safari

**Comment by SlippyJimmy** [comment]
图片搞成缩略图了，重新提交
[缩小](https://ws1.sinaimg.cn/large/007rzGmgly1fxrjjrvud7j30xe0nvk8t.jpg)
[放大](https://ws1.sinaimg.cn/large/007rzGmgly1fxrjjsf1iij31hc0u0kft.jpg)

**Comment by Siphils** [comment]
我用的是[bootstrap的网格系统](https://v3.bootcss.com/css/#grid-options) ，`.container`最大宽度只会达到`1160px`  
之前没考虑过大分辨率下的问题。。。
