### ISSUE TITLE
代码块显示问题

### ISSUE THREAD

**Issue by fallenleaves03** [Siphils/Typecho-Theme-Aria#16]
如图
每个函数换行大括号会往后移一个字符
请问如何解决
![](https://ws1.sinaimg.cn/large/007wuWW6gy1fyet2vyxsoj307h03tweh.jpg)
![](https://ws1.sinaimg.cn/large/007wuWW6gy1fyet4hj6sij305m033747.jpg)

**Comment by Siphils** [comment]
fixed in [97c5e65](https://github.com/Siphils/Typecho-Theme-Aria/commit/97c5e65e0293154da7479c38ebbf97e4bc9da4e4)
