### ISSUE TITLE
手机端chrome显示问题

### ISSUE THREAD

**Issue by Makebignew** [Siphils/Typecho-Theme-Aria#18]
[chrome](https://wx3.sinaimg.cn/large/0060lm7Tly1fyptn8352oj30u01cek5e.jpg)
如上图，手机端chrome显示错位，页面可以缩放，右侧出现留白，比例不协调

**Comment by Siphils** [comment]
提供一下操作系统和浏览器版本信息。。

**Comment by Makebignew** [comment]
@Siphils Chrome 73.0.3643.0.  System: Android 8.0

**Comment by Siphils** [comment]
[![20190102000040.jpg](https://i.loli.net/2019/01/02/5c2b8ee8c5264.jpg)](https://i.loli.net/2019/01/02/5c2b8ee8c5264.jpg)  
Chrome Dev 73.0.3643.0 Android 8.1（和8.0应该影响不大）下测试没有什么问题啊。
是不是使用了别的什么插件导致的？

**Comment by Makebignew** [comment]
@Siphils 确实应该只是个别问题，更换Chrome版本后，我这边显示也正常了

**Comment by Siphils** [comment]
> @Siphils 确实应该只是个别问题，更换Chrome版本后，我这边显示也正常了

😁我测试的时候也是用的和你产生问题时的同一个版本的浏览器 Chrome Dev 73.0.3643.0
可能是有别的什么影响了吧
