### ISSUE TITLE
文档归档页面

### ISSUE THREAD

**Issue by 490694561** [Siphils/Typecho-Theme-Aria#2]
文章归档页面当文章数量超过一定数量之后自动省略是正常情况吗

**Comment by Siphils** [comment]
感谢反馈bug，这是我写代码时候的疏漏。暂时解决办法：
打开`page-archives.php`文件，找到第`32`行处：
```php
<?php $this->widget('Widget_Contents_Post_Recent')->to($post);?>
```
将此行修改为：
```php
<?php $this->widget('Widget_Contents_Post_Recent','pageSize=10000')->to($post);?>
```
下个小版本我会修复这个BUG。

**Comment by Siphils** [comment]
fixed in [7c285e2](https://github.com/Siphils/Typecho-Theme-Aria/commit/815092384986e2c8bb527ecea037836b29a5285d)
