### ISSUE TITLE
文章底部二维码加载失败

### ISSUE THREAD

**Issue by liuqi19990825** [Siphils/Typecho-Theme-Aria#20]
如题
![image](https://user-images.githubusercontent.com/45392421/51919825-31d2de80-241f-11e9-88d9-5b56dd4e91f3.png)
打开其他文章，依然是这样。
![image](https://user-images.githubusercontent.com/45392421/51919884-4c0cbc80-241f-11e9-933e-239075d9d3ae.png)

**Comment by Siphils** [comment]
500 错误多是由于服务器问题引起

**Comment by liuqi19990825** [comment]
> 500错误多是由于服务器问题引起

查明是没有安装php-gd扩展，谢谢大佬回复(*^_^*)
