### ISSUE TITLE
请问一下友链怎么并排展示呀~?

### ISSUE THREAD

**Issue by AGLcaicai** [Siphils/Typecho-Theme-Aria#22]
用了友链的那个[link-box]之后，友链是一列往下展示的
![_20190201204038](https://user-images.githubusercontent.com/21209250/52148474-a85f1e80-2661-11e9-9efb-982ad5420e25.png)
效果图
![_20190201203833](https://user-images.githubusercontent.com/21209250/52148377-60d89280-2661-11e9-877b-9a69949f12b4.png)
求助如何变成并排展示

**Comment by Siphils** [comment]
> [链接盒子](https://github.com/Siphils/Typecho-Theme-Aria/wiki/%E8%BF%9B%E9%98%B6%E4%BD%BF%E7%94%A8#%E9%93%BE%E6%8E%A5%E7%9B%92%E5%AD%90%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5  )  
```
[link-box]
[link-item .....]
[link-item .....]
[/link-box]
[link-box]
[link-item .....]
[link-item .....]
[/link-box]
```
