### ISSUE TITLE
自定义JS那里写的是链接还是源码？

### ISSUE THREAD

**Issue by inkhin** [Siphils/Typecho-Theme-Aria#23]
帮助文档没有详细说明，自己尝试过程中链接不显示，试了一下源码，网站就崩了。个人设置都空了，网站出了大问题。帮助文档那里是什么意思？看不懂，麻烦说一下，十分感谢了

**Comment by Siphils** [comment]
直接写`javascript`代码。不需要带上`<script></script>`标签。
如果是要加类似`<script src="">`这类的话可以在`底部自定义内容`或者`顶部自定义内容`里插入。

**Comment by inkhin** [comment]
嗯嗯，好的，真的十分感谢啦

**Comment by Siphils** [comment]
关于网站崩了、设置空了，我想可能是别的原因，因为比较严重的BUG一般我在测试的时候会尽可能的已经排除掉了。

**Comment by inkhin** [comment]
嗯嗯，没事，我就是求知欲太严重，学到东西就算服务器崩了都没事(´,,•ω•,,‘)
