### ISSUE TITLE
打开文章时无法输出内容

### ISSUE THREAD

**Issue by White-Clouds** [Siphils/typecho-theme-Aria#25]
依然是EditorMD编辑器插件的问题，安照之前的解决方法加上了一段JS后还是没有解决。
![2019-04-16](https://user-images.githubusercontent.com/36442882/56184884-492b6c00-600b-11e9-94e8-8cd8cae10dfa.png)

**Comment by Siphils** [comment]
不知道这个有没有在后端渲染的功能，实在需要可以先暂时关闭pjax功能
