### ISSUE TITLE
提示没有ShortCode.php

### ISSUE THREAD

**Issue by MarkKobs** [Siphils/Typecho-Theme-Aria#3]
Warning: require_once(lib/Shortcode.php): failed to open stream: No such file or directory in /www/wwwroot/kobs.site/usr/themes/Aria2/functions.php on line 6

Fatal error: require_once(): Failed opening required 'lib/Shortcode.php' (include_path='.:/www/server/php/71/lib/php:/www/wwwroot/kobs.site/var:/www/wwwroot/kobs.site/usr/plugins') in /www/wwwroot/kobs.site/usr/themes/Aria2/functions.php on line 6

**Comment by Siphils** [comment]
应该是主题目录名的问题，`Aria2`修改为`Aria`
