### ISSUE TITLE
wiki 中导航栏创建-归档标签时用了旧的语法

### ISSUE THREAD

**Issue by lpp12138** [Siphils/typecho-theme-Aria#36]
原文：
{
    "text": "归档",
    "href": "https://eriri.ink/archives.html",
    "icon": "icon-aria-archives"
} 
应为"icon": "iconfont icon-aria-archives"
顺便一提，有没有支持可能用别的头像源设置呢？
（虽然自己魔改主题是可以做到的，但要是后续有更新的话会比较麻烦）
以及本地图片更快捷的引用方式

**Comment by Siphils** [comment]
感谢指出wiki错误。
别的头像源指的是自定义Gravatar源还是使用别的头像？

**Comment by lpp12138** [comment]
自定义Gravatar源,或者拉取别的社交媒体头像之类的,我之前查到有人改过,应该是加个输入框的事?(我写C#的不是很懂)

**Comment by Siphils** [comment]
> 自定义Gravatar源,或者拉取别的社交媒体头像之类的,我之前查到有人改过,应该是加个输入框的事?(我写C#的不是很懂)

自定义Gravatar源v.1.9.0已经支持了，社交媒体头像目前没有考虑。

**Comment by lpp12138** [comment]
> > 自定义Gravatar源,或者拉取别的社交媒体头像之类的,我之前查到有人改过,应该是加个输入框的事?(我写C#的不是很懂)
> 
> 自定义Gravatar源v.1.9.0已经支持了，社交媒体头像目前没有考虑。

瞭,谢谢
