### ISSUE TITLE
关于使用EditorMD编辑器后页面内代码解析问题

### ISSUE THREAD

**Issue by White-Clouds** [Siphils/typecho-theme-Aria#38]
![Snipaste_2020-03-06_14-16-01](https://user-images.githubusercontent.com/36442882/76057846-9a6d8280-5f72-11ea-80ff-cccf5df042df.png)
如同，无论是使用EditorMD的行内代码还是代码块都会超出页面。
不知道怎么解决，求解。

**Comment by Siphils** [comment]
截止v1.9.0暂不支持EditorMD，仅支持原生编辑器
