### ISSUE TITLE
评论里的emoji不显示

### ISSUE THREAD

**Issue by luabish** [Siphils/Typecho-Theme-Aria#4]
请问emoji显示需要额外配置什么吗？我的OwO设置没有填写

**Comment by Siphils** [comment]
> 让 Typecho 支持 emoji 表情显示
> https://www.uskvm.com/p/33.html 
需要修改数据库字符集。建议在测试的时候先备份下数据库以防误操作。

**Comment by luabish** [comment]
> > 让 Typecho 支持 emoji 表情显示
> > https://www.uskvm.com/p/33.html
> 
> 需要修改数据库字符集。建议在测试的时候先备份下数据库以防误操作。

多谢，改了comment那一列的字符集，以及客户端的连接字符集，可以了。
