### ISSUE TITLE
文章列表的圆角和文字并没有很好的匹配

### ISSUE THREAD

**Issue by Zhang-Siyang** [Siphils/Typecho-Theme-Aria#7]
![2018-11-17 14 38 06](https://user-images.githubusercontent.com/22904269/48658067-77b21480-ea76-11e8-960b-a4aa26ec7806.png)

很僵硬，就像早期的全面屏一样

当然，个人观点

**Comment by Siphils** [comment]
这主题一开始是按照自己的喜好和习惯去做的。
设计这一块我搞的可能不是很好，有更好的想法可以提出来。

**Comment by Zhang-Siyang** [comment]
很遗憾，我只是从用户视角看的，这个issue可以关闭了
