### ISSUE TITLE
开启评论审核功能，评论时会报错

### ISSUE THREAD

**Issue by P3TERX** [Siphils/Typecho-Theme-Aria#8]
开启了评论审核，以访客身份评论，然后就报错了。审核后能正常显示。
![image](https://user-images.githubusercontent.com/25927179/48678916-e2716600-ebc4-11e8-93d3-7a9f9983f6c8.png)

```
Notice: Undefined index: text in /www/.../usr/themes/Aria/functions.php on line 569

Notice: Undefined index: parent in /www/.../usr/themes/Aria/functions.php on line 589

Notice: Undefined index: author in /www/.../usr/themes/Aria/functions.php on line 593

@
```
我换成默认主题显示正常
![snipaste20181119_063131](https://user-images.githubusercontent.com/25927179/48678948-15b3f500-ebc5-11e8-8c7e-ae0f3d82d8a1.png)

看了下 `functions.php` 三个位置分别是 `$text = $result['text'];`、`$parent = $prow['parent'];`、`$author = $arow['author'];`

**Comment by Siphils** [comment]
过几天有空我看看，这两天没空。估计是评论的状态输出不同引起的错误。

**Comment by P3TERX** [comment]
![tim 20180116175226](https://user-images.githubusercontent.com/25927179/49400141-53e11500-f77e-11e8-9139-8a4245ee9cb0.jpg)
